In [3]:
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

df = pd.read_csv("2004-2021.csv",sep = "\t")

In [4]:
df.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [5]:
df.columns

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO'],
      dtype='str')

In [6]:
df.rename(columns = {"DATA INICIAL":"START DATE"},inplace = True)

In [7]:
old_name = ['START DATE', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO']

In [8]:
new_name = [
    'START DATE', 
    'END DATE', 
    'REGION', 
    'STATE', 
    'PRODUCT',
    'NUMBER OF STATIONS SURVEYED', 
    'UNIT OF MEASUREMENT',
    'AVERAGE RESALE PRICE', 
    'RESALE STANDARD DEVIATION', 
    'MINIMUM RESALE PRICE',
    'MAXIMUM RESALE PRICE', 
    'AVERAGE RESALE MARGIN',
    'RESALE COEFFICIENT OF VARIATION', 
    'AVERAGE DISTRIBUTION PRICE',
    'DISTRIBUTION STANDARD DEVIATION', 
    'MINIMUM DISTRIBUTION PRICE',
    'MAXIMUM DISTRIBUTION PRICE', 
    'DISTRIBUTION COEFFICIENT OF VARIATION'
]

In [9]:
print(len(df.columns))

18

In [10]:
for i in range(len(df.columns)):
    df.rename(columns = {old_name[i]:new_name[i]},inplace = True)

In [11]:
df.head()

,START DATE,END DATE,REGION,STATE,PRODUCT,NUMBER OF STATIONS SURVEYED,UNIT OF MEASUREMENT,AVERAGE RESALE PRICE,RESALE STANDARD DEVIATION,MINIMUM RESALE PRICE,MAXIMUM RESALE PRICE,AVERAGE RESALE MARGIN,RESALE COEFFICIENT OF VARIATION,AVERAGE DISTRIBUTION PRICE,DISTRIBUTION STANDARD DEVIATION,MINIMUM DISTRIBUTION PRICE,MAXIMUM DISTRIBUTION PRICE,DISTRIBUTION COEFFICIENT OF VARIATION
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [12]:
df.columns

Index(['START DATE', 'END DATE', 'REGION', 'STATE', 'PRODUCT',
       'NUMBER OF STATIONS SURVEYED', 'UNIT OF MEASUREMENT',
       'AVERAGE RESALE PRICE', 'RESALE STANDARD DEVIATION',
       'MINIMUM RESALE PRICE', 'MAXIMUM RESALE PRICE', 'AVERAGE RESALE MARGIN',
       'RESALE COEFFICIENT OF VARIATION', 'AVERAGE DISTRIBUTION PRICE',
       'DISTRIBUTION STANDARD DEVIATION', 'MINIMUM DISTRIBUTION PRICE',
       'MAXIMUM DISTRIBUTION PRICE', 'DISTRIBUTION COEFFICIENT OF VARIATION'],
      dtype='str')

In [13]:
df.drop('UNIT OF MEASUREMENT' , axis = 1 , inplace = True)

In [14]:
# df.rename(columns = {"DATA INICIAL":"START DATE"},inplace = True)

In [16]:
df

,START DATE,END DATE,REGION,STATE,PRODUCT,NUMBER OF STATIONS SURVEYED,AVERAGE RESALE PRICE,RESALE STANDARD DEVIATION,MINIMUM RESALE PRICE,MAXIMUM RESALE PRICE,AVERAGE RESALE MARGIN,RESALE COEFFICIENT OF VARIATION,AVERAGE DISTRIBUTION PRICE,DISTRIBUTION STANDARD DEVIATION,MINIMUM DISTRIBUTION PRICE,MAXIMUM DISTRIBUTION PRICE,DISTRIBUTION COEFFICIENT OF VARIATION
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [ ]:
import pandas as pd
df = pd.read_csv("2004-2021.csv")
df.drop(columns=["UNIT OF MEASUREMENT"],axis=1)

In [ ]:
df.drop(columns = {"UNIT OF MEASUREMENT"},inplace = True)

In [ ]:
df.drop(columns = ({"UNIT OF MEASUREMENT"}),inplace=True)

In [ ]:
df.head()

In [ ]:

df.drop("UNIT OF MEASUREMENT",axis=1,inplace=True)
df.head()

In [17]:
df.drop("RESALE STANDARD DEVIATION",axis=1,inplace=True)
df.head()

,START DATE,END DATE,REGION,STATE,PRODUCT,NUMBER OF STATIONS SURVEYED,AVERAGE RESALE PRICE,MINIMUM RESALE PRICE,MAXIMUM RESALE PRICE,AVERAGE RESALE MARGIN,RESALE COEFFICIENT OF VARIATION,AVERAGE DISTRIBUTION PRICE,DISTRIBUTION STANDARD DEVIATION,MINIMUM DISTRIBUTION PRICE,MAXIMUM DISTRIBUTION PRICE,DISTRIBUTION COEFFICIENT OF VARIATION
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,1.288,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,1.162,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,1.389,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,1.262,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,1.181,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082